Update docker.yml

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -2,6 +2,7 @@ name: Build and Deploy Docker Image
 on:
   push:
     branches: [ "main" ]
+
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -11,7 +12,7 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
         with:
-         persist-credentials: true   # permite push con GITHUB_TOKEN
+          persist-credentials: true   # permite push con token personal
 
       # 2. Login a Docker Hub
       - name: Docker Hub login
@@ -37,14 +38,14 @@ jobs:
         run: |
           sed -i "s|tag: .*|tag: \"$IMAGE_TAG\"|" $GITHUB_WORKSPACE/helm/flask-app/values.yaml
 
-      # 6. Commit y push seguro usando HELM_GITHUB_USER y HELM_GITHUB_TOKEN
+      # 6. Configurar Git y push seguro usando HELM_GITHUB_USER y HELM_GITHUB_TOKEN
       - name: Commit and push updated values.yaml
         run: |
           git config user.name "${{ secrets.HELM_GITHUB_USER }}"
           git config user.email "${{ secrets.HELM_GITHUB_USER }}@users.noreply.github.com"
           git add $GITHUB_WORKSPACE/helm/flask-app/values.yaml
           git commit -m "chore: update Docker image to $IMAGE_TAG" || echo "No changes to commit"
-          git push https://${{ secrets.HELM_GITHUB_USER }}:${{ secrets.HELM_GITHUB_TOKEN }}@github.com/luismuma/techwave_web_K8s.git main --force || echo "Push failed, but workflow continues"
+          git push https://${{ secrets.HELM_GITHUB_USER }}:${{ secrets.HELM_GITHUB_TOKEN }}@github.com/luismuma/techwave_web_helm.git main --force || echo "Push failed, but workflow continues"
 
       # 7. Verificar imagen construida (opcional)
       - name: Verify Docker image
